:git:
  #
  # Shell command to push git repo to remote
  #
  :push: |
    sudo -u <%= user %> ssh-agent /bin/bash -c "cd <%= directory %> && ssh-add <%= identity %> && git push <%= remote %> <%= branch %> "
  #
  # Regular git commits locally
  #
  :commit: |

    sudo -u <%= user %>  /bin/bash -c "cd <%= directory %> && git add . && git commit -m '<%= message %>' "
